/**
 * Notification Models Module
 * 
 * Contains type definitions for user notifications and preferences.
 */

import type { ISODateString } from '../api/common';

/**
 * Available notification types in the system
 * Categorizes notifications for handling and display
 */
export type NotificationType = 
    | 'payment_reminder'    // Payment reminder
    | 'achievement'         // Achievement reached
    | 'goal_progress'       // Progress on a goal
    | 'tip'                 // Financial tip
    | 'announcement';       // Announcement or news

/**
 * Notification origins
 * Indicates how the notification was created
 */
export type NotificationOrigin = 
    | 'automatic'           // Automatically generated by the system
    | 'manual';             // Manually created by an administrator

/**
 * Notification read status
 * Tracks whether a user has seen the notification
 */
export type NotificationStatus = 
    | 'unread'              // Unread
    | 'read'                // Read

/**
 * Type for notification metadata
 * Stores additional context-specific data for notifications
 */
export interface NotificationMetadata {
    [key: string]: string | number | boolean | null | undefined;
}

/**
 * Interface for notifications
 * Represents a user notification with all its properties
 */
export interface Notification {
    _id: string;                 // Unique identifier
    user_id: string;             // User who receives the notification
    type: NotificationType;      // Type of notification
    title: string;               // Short title
    message: string;             // Brief notification message
    status: NotificationStatus;  // Whether it's been read
    origin: NotificationOrigin;  // How it was created
    createdAt: ISODateString;    // When it was created
    updatedAt: ISODateString;    // When it was last updated
    // Optional fields based on notification type
    metadata?: NotificationMetadata; // Additional data based on type
    expiresAt?: ISODateString;  // When the notification expires
    content?: string;           // Extended HTML content for detailed notifications
}

/**
 * Interface for user notification preferences
 * Controls which notifications a user receives and how
 */
export interface NotificationPreferences {
    inApp: {
        enabled: boolean;        // Master toggle for in-app notifications
        types: {
            [key in NotificationType]: boolean; // Toggle for each notification type
        };
    };
    email: {
        enabled: boolean;        // Master toggle for email notifications
        types: {
            [key in NotificationType]: boolean; // Toggle for each notification type
        };
    };
} 